### ISSUE TITLE
прошу проверить ДЗ

### ISSUE THREAD

**Issue by Alanrus** [Alanrus/10-JdbcTemplate-advanced-#1]
@coursar

**Comment by coursar** [comment]
Эта задача была рассмотрена на лекциях

**Comment by Alanrus** [comment]
Ильназ, здравствуйте. я не понял в чем проблема. Я же сделал дз точно по ТЗ. Да, я использовал наши лекционные примеры как основу. 

Что нужно было сделать по – другому, чтобы сдать дз?

 �
